version: '3.8'
services:
    nginx:
        image: nginx:latest
        container_name: chatboard-nginx
        ports:
            - "8080:80"
        volumes:
            - ./chatboard:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - chatboard-net

    php:
        image: php:8.2-fpm
        container_name: chatboard-php
        volumes:
            - ./chatboard:/var/www/html
        networks:
            - chatboard-net

networks:
    chatboard-net:
        driver: bridge
